[tools]
bun = "latest"
node = "24"
pnpm = "latest"

rust = "latest"
just = "latest"
uv = "latest"

claude = "latest"
codex = "latest"
"npm:agent-browser" = "latest"
viteplus = "latest"
"npm:t3" = "latest"
python = "latest"

[settings]
minimum_release_age_excludes = ["bun", "node", "pnpm", "uv", "claude", "codex"]
