# Taps
tap "oven-sh/bun"
tap "anomalyco/tap"

# Essential
brew "bundler-completion"
brew "stow"
brew "git"
brew "curl"
brew "wget"
brew "perl"
brew "openssl"
brew "pkg-config"

# Core system
brew "zsh"
brew "neovim"
brew "tree"
brew "jq"
brew "htop"
brew "postgresql@15"
brew "bat"
brew "fd"
brew "fzf"
brew "zoxide"
brew "gh"
brew "eza"
brew "ripgrep"
brew "dust"
brew "btop"
brew "starship"
brew "hyperfine"

# Dev tools
brew "mosh"
brew "tmux"
brew "zellij"
brew "lazygit"
brew "worktrunk"

# AI tools
brew "gemini-cli"
brew "opencode"
brew "agent-browser"
brew "googleworkspace-cli"

brew "docker"
brew "docker-compose"

brew "fontconfig"
cask "font-jetbrains-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"

cask "raycast"
cask "ghostty"
cask "cmux"
